### ISSUE TITLE
How datasets are made

### ISSUE THREAD

**Issue by yasailiu** [mapeAAU/3D-ZeF#1]
I would like to know what software tools the dataset in your article "3D-ZeF: A 3D Zebrafish Tracking Benchmark Dataset" was made

**Comment by mapeAAU** [comment]
Hi Yasailiu, we used a custom tool developed in our lab to annotate the 3D-ZeF dataset. All annotations were done manually and verified by multiple experts. 
However, the dataset only contains bounding boxes and point annotations, so the majority of public annotation tools can be used for similar tasks.

**Comment by yasailiu** [comment]
Thank you for your reply.Is the annotation tool open source? Or is there any alternative tool?

**Comment by mapeAAU** [comment]
The annotation tool we used is not open source, but there are tons of great annotation tools on the Internet. 
Here are some examples: 
[LabelMe](https://github.com/wkentaro/labelme)
[CVAT](https://www.cvat.ai/), 
[VoTT](https://github.com/microsoft/VoTT), 
[SuperAnnotate](https://www.superannotate.com/), 
etc. etc.
